# Generated by Django 5.2.7 on 2025-10-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drfpost',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='path'),
        ),
    ]
