# Generated by Django 5.2.6 on 2025-09-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='nim',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
